---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-public-images/gpdb7-centos7-test
    tag: latest

inputs:
- name: gpdb_src
- name: bin_gpdb_centos7
- name: bin_gpdb_ubuntu18.04
- name: bin_gpdb_rhel8
- name: bin_gpdb_clients_centos7
- name: bin_gpdb_clients_rhel8
- name: bin_gpdb_clients_ubuntu18.04

outputs:
- name: release_candidates

params:
  RC_BUILD_TYPE_GCS:

run:
  path: bash
  args:
  - -ec
  - |
    gpdb_semver=$(gpdb_src/getversion | cut -d' ' -f1)
    cp -v bin_gpdb_centos7/bin_gpdb.tar.gz release_candidates/server-rc-${gpdb_semver}-rhel7_x86_64${RC_BUILD_TYPE_GCS}.tar.gz
    cp -v bin_gpdb_ubuntu18.04/bin_gpdb.tar.gz release_candidates/server-rc-${gpdb_semver}-ubuntu18.04_x86_64${RC_BUILD_TYPE_GCS}.tar.gz
    cp -v bin_gpdb_rhel8/bin_gpdb.tar.gz release_candidates/server-rc-${gpdb_semver}-rhel8_x86_64${RC_BUILD_TYPE_GCS}.tar.gz
    cp -v bin_gpdb_clients_centos7/bin_gpdb_clients.tar.gz release_candidates/clients-rc-${gpdb_semver}-rhel7_x86_64${RC_BUILD_TYPE_GCS}.tar.gz
    cp -v bin_gpdb_clients_rhel8/bin_gpdb_clients.tar.gz release_candidates/clients-rc-${gpdb_semver}-rhel8_x86_64${RC_BUILD_TYPE_GCS}.tar.gz
    cp -v bin_gpdb_clients_ubuntu18.04/bin_gpdb_clients.tar.gz release_candidates/clients-rc-${gpdb_semver}-ubuntu18.04_x86_64${RC_BUILD_TYPE_GCS}.tar.gz