platform: linux
image_resource:
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-public-images/gpdb7-centos7-test
    tag: latest
inputs:
  - name: gpdb_src
run:
  path: gpdb_src/concourse/scripts/unit_tests_gpcloud.bash
